---
- name: basic set up for all hosts 
  hosts: all
  become: true
  roles:  
    - { role: common }
    - { role: motd }
#    - { role: firewalld }
    - { role: hardening }
    - { role: fail2ban }

